### ISSUE TITLE
When PR squash and merge, it no longer moves Wrike task to Done/Complete

### ISSUE THREAD

**Issue by gabrieledcjr** [valerauko/wrike-ist#16] opened 2022-01-25 00:47 UTC
Adding the PR link in the Wrike task still works. But once we squash and merge the PR, it use to work a few weeks ago, but it no longer works. I've tested, moving the PR to In progress and running the workflow, but it no longer moves it to Done/Complete.

**Comment by valerauko** [comment] 2022-01-25 03:43
Okay that's weird. There hasn't been a release of this action in months so unless Github Actions changed how things work such a change should not happen...

I'll see if I can reproduce the issue

**Comment by valerauko** [comment] 2022-02-03 03:13
Hmm I've checked the behavior in a repository and I can't reproduce the issue. Do you get any errors from the Github Action? Does it fail in some way?

**Comment by gabrieledcjr** [comment] 2022-02-03 04:18
We are testing a theory. We believe that if the permalink is the only thing in the PR, we think it doesn't trigger the action. But if we add at least one line then the permalink in another line it works.

**Comment by valerauko** [comment] 2022-09-21 12:18
I tested with your hypothesis too and sadly I cannot reproduce the problem. I'll close this issue for now, but feel free to reopen if the problem persists.

**Closed as completed by valerauko** 2022-09-21 12:18 UTC
